package it.nextworks.nfvmano.timeo.ro;

public enum ResourceAllocationStatus {

	INIT,
	CREATING_VLS_NETS,
	CREATING_VLS_SUBNETS,
	CREATING_VLS_SAPS,
	CREATED_VLS,
	CREATING_VNF,
	CREATED_VNF,
	CONFIGURING_VNF,
	CONFIGURED_VNF,
	CREATING_NETWORK_CONNECTIONS,
	CREATED_NETWORK_CONNECTIONS,
	TERMINATING_VNF,
	TERMINATED_VNF,
	TERMINATING_NETWORK_CONNECTIONS,
	TERMINATED_NETWORK_CONNECTIONS,
	TERMINATING_VLS_SAPS,
	TERMINATING_VLS_SUBNETS,
	TERMINATING_NETS,
	TERMINATED_NETS,
	FAILED
	
}
