/*
 * Configuration Manager API
 * The API of the 5GT Monitoring Configuration Manager.
 *
 * OpenAPI spec version: 0.6
 * Contact: m.capitani@nextworks.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Alert;
import io.swagger.client.model.AlertDescription;
import io.swagger.client.model.AlertQueryResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlertApi
 */
@Ignore
public class AlertApiTest {

    private final AlertApi api = new AlertApi();

    /**
     * Delete alert
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAlertTest() throws ApiException {
        String alertId = null;
        Object response = api.deleteAlert(alertId);

        // TODO: test validations
    }
    /**
     * Get alert details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlertTest() throws ApiException {
        String alertId = null;
        Alert response = api.getAlert(alertId);

        // TODO: test validations
    }
    /**
     * Get all alerts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAlertsTest() throws ApiException {
        AlertQueryResult response = api.getAllAlerts();

        // TODO: test validations
    }
    /**
     * Create new alert
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postAlertTest() throws ApiException {
        AlertDescription body = null;
        Alert response = api.postAlert(body);

        // TODO: test validations
    }
    /**
     * Update alert
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putAlertTest() throws ApiException {
        Alert body = null;
        String alertId = null;
        Alert response = api.putAlert(body, alertId);

        // TODO: test validations
    }
}
