/*
 * tapi-arof API
 * tapi-arof API generated from tapi-arof.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LocalClass;
import io.swagger.client.model.NameAndValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Rule
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-09T14:13:03.153+02:00")
public class Rule {
  @SerializedName("local-id")
  private String localId = null;

  @SerializedName("name")
  private List<NameAndValue> name = null;

  /**
   * Gets or Sets ruleType
   */
  @JsonAdapter(RuleTypeEnum.Adapter.class)
  public enum RuleTypeEnum {
    FORWARDING("FORWARDING"),
    
    CAPACITY("CAPACITY"),
    
    COST("COST"),
    
    TIMING("TIMING"),
    
    RISK("RISK"),
    
    GROUPING("GROUPING");

    private String value;

    RuleTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RuleTypeEnum fromValue(String text) {
      for (RuleTypeEnum b : RuleTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<RuleTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RuleTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RuleTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return RuleTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("rule-type")
  private RuleTypeEnum ruleType = null;

  /**
   * Gets or Sets forwardingRule
   */
  @JsonAdapter(ForwardingRuleEnum.Adapter.class)
  public enum ForwardingRuleEnum {
    MAY_FORWARD_ACROSS_GROUP("MAY_FORWARD_ACROSS_GROUP"),
    
    MUST_FORWARD_ACROSS_GROUP("MUST_FORWARD_ACROSS_GROUP"),
    
    CANNOT_FORWARD_ACROSS_GROUP("CANNOT_FORWARD_ACROSS_GROUP"),
    
    NO_STATEMENT_ON_FORWARDING("NO_STATEMENT_ON_FORWARDING");

    private String value;

    ForwardingRuleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ForwardingRuleEnum fromValue(String text) {
      for (ForwardingRuleEnum b : ForwardingRuleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ForwardingRuleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ForwardingRuleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ForwardingRuleEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ForwardingRuleEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("forwarding-rule")
  private ForwardingRuleEnum forwardingRule = null;

  @SerializedName("override-priority")
  private String overridePriority = null;

  public Rule localId(String localId) {
    this.localId = localId;
    return this;
  }

   /**
   * Get localId
   * @return localId
  **/
  @ApiModelProperty(value = "")
  public String getLocalId() {
    return localId;
  }

  public void setLocalId(String localId) {
    this.localId = localId;
  }

  public Rule name(List<NameAndValue> name) {
    this.name = name;
    return this;
  }

  public Rule addNameItem(NameAndValue nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<NameAndValue>();
    }
    this.name.add(nameItem);
    return this;
  }

   /**
   * List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.
   * @return name
  **/
  @ApiModelProperty(value = "List of names. A property of an entity with a value that is unique in some namespace but may change during the life of the entity. A name carries no semantics with respect to the purpose of the entity.")
  public List<NameAndValue> getName() {
    return name;
  }

  public void setName(List<NameAndValue> name) {
    this.name = name;
  }

  public Rule ruleType(RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
    return this;
  }

   /**
   * Get ruleType
   * @return ruleType
  **/
  @ApiModelProperty(value = "")
  public RuleTypeEnum getRuleType() {
    return ruleType;
  }

  public void setRuleType(RuleTypeEnum ruleType) {
    this.ruleType = ruleType;
  }

  public Rule forwardingRule(ForwardingRuleEnum forwardingRule) {
    this.forwardingRule = forwardingRule;
    return this;
  }

   /**
   * Get forwardingRule
   * @return forwardingRule
  **/
  @ApiModelProperty(value = "")
  public ForwardingRuleEnum getForwardingRule() {
    return forwardingRule;
  }

  public void setForwardingRule(ForwardingRuleEnum forwardingRule) {
    this.forwardingRule = forwardingRule;
  }

  public Rule overridePriority(String overridePriority) {
    this.overridePriority = overridePriority;
    return this;
  }

   /**
   * Get overridePriority
   * @return overridePriority
  **/
  @ApiModelProperty(value = "")
  public String getOverridePriority() {
    return overridePriority;
  }

  public void setOverridePriority(String overridePriority) {
    this.overridePriority = overridePriority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rule rule = (Rule) o;
    return Objects.equals(this.localId, rule.localId) &&
        Objects.equals(this.name, rule.name) &&
        Objects.equals(this.ruleType, rule.ruleType) &&
        Objects.equals(this.forwardingRule, rule.forwardingRule) &&
        Objects.equals(this.overridePriority, rule.overridePriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localId, name, ruleType, forwardingRule, overridePriority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rule {\n");
    
    sb.append("    localId: ").append(toIndentedString(localId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ruleType: ").append(toIndentedString(ruleType)).append("\n");
    sb.append("    forwardingRule: ").append(toIndentedString(forwardingRule)).append("\n");
    sb.append("    overridePriority: ").append(toIndentedString(overridePriority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

