package it.nextworks.nfvmano.timeo.nso;

public enum InternalNsStatus {

	TO_BE_INSTANTIATED,
	COMPUTING_RESOURCES,
	ALLOCATING_NS_VLS,
	CREATING_VNFS,
	CONFIGURING_VNFS,
	CREATING_CONNECTIVITY,
	ALLOCATED,
	TERMINATING_VNFS,
	TERMINATING_CONNECTIVITY,
	REMOVING_NS_VLS,
	RELEASING_COMPUTED_RESOURCES,
	TERMINATED,
	FAILED
	
}
