/*
 * tapi-sdm API
 * tapi-sdm API generated from tapi-sdm.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OtsiRoutingSpec
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-09T13:10:07.918+02:00")
public class OtsiRoutingSpec {
  @SerializedName("optical-routing-strategy")
  private String opticalRoutingStrategy = null;

  public OtsiRoutingSpec opticalRoutingStrategy(String opticalRoutingStrategy) {
    this.opticalRoutingStrategy = opticalRoutingStrategy;
    return this;
  }

   /**
   * Get opticalRoutingStrategy
   * @return opticalRoutingStrategy
  **/
  @ApiModelProperty(value = "")
  public String getOpticalRoutingStrategy() {
    return opticalRoutingStrategy;
  }

  public void setOpticalRoutingStrategy(String opticalRoutingStrategy) {
    this.opticalRoutingStrategy = opticalRoutingStrategy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OtsiRoutingSpec otsiRoutingSpec = (OtsiRoutingSpec) o;
    return Objects.equals(this.opticalRoutingStrategy, otsiRoutingSpec.opticalRoutingStrategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opticalRoutingStrategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OtsiRoutingSpec {\n");
    
    sb.append("    opticalRoutingStrategy: ").append(toIndentedString(opticalRoutingStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

