/*
 * tapi-connectivity API
 * tapi-connectivity API generated from tapi-connectivity@2018-03-07.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConnectivityConstraint;
import io.swagger.client.model.ConnectivityServiceEndPoint;
import io.swagger.client.model.ResilienceConstraint;
import io.swagger.client.model.TopologyConstraint;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UpdateConnectivityServiceRPCInputSchema
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-07T13:54:22.249+02:00")
public class UpdateConnectivityServiceRPCInputSchema {
  @SerializedName("resilience-constraint")
  private List<ResilienceConstraint> resilienceConstraint = null;

  @SerializedName("service-id-or-name")
  private String serviceIdOrName = null;

  @SerializedName("topo-constraint")
  private TopologyConstraint topoConstraint = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("end-point")
  private ConnectivityServiceEndPoint endPoint = null;

  @SerializedName("conn-constraint")
  private ConnectivityConstraint connConstraint = null;

  public UpdateConnectivityServiceRPCInputSchema resilienceConstraint(List<ResilienceConstraint> resilienceConstraint) {
    this.resilienceConstraint = resilienceConstraint;
    return this;
  }

  public UpdateConnectivityServiceRPCInputSchema addResilienceConstraintItem(ResilienceConstraint resilienceConstraintItem) {
    if (this.resilienceConstraint == null) {
      this.resilienceConstraint = new ArrayList<ResilienceConstraint>();
    }
    this.resilienceConstraint.add(resilienceConstraintItem);
    return this;
  }

   /**
   * Get resilienceConstraint
   * @return resilienceConstraint
  **/
  @ApiModelProperty(value = "")
  public List<ResilienceConstraint> getResilienceConstraint() {
    return resilienceConstraint;
  }

  public void setResilienceConstraint(List<ResilienceConstraint> resilienceConstraint) {
    this.resilienceConstraint = resilienceConstraint;
  }

  public UpdateConnectivityServiceRPCInputSchema serviceIdOrName(String serviceIdOrName) {
    this.serviceIdOrName = serviceIdOrName;
    return this;
  }

   /**
   * Get serviceIdOrName
   * @return serviceIdOrName
  **/
  @ApiModelProperty(value = "")
  public String getServiceIdOrName() {
    return serviceIdOrName;
  }

  public void setServiceIdOrName(String serviceIdOrName) {
    this.serviceIdOrName = serviceIdOrName;
  }

  public UpdateConnectivityServiceRPCInputSchema topoConstraint(TopologyConstraint topoConstraint) {
    this.topoConstraint = topoConstraint;
    return this;
  }

   /**
   * Get topoConstraint
   * @return topoConstraint
  **/
  @ApiModelProperty(value = "")
  public TopologyConstraint getTopoConstraint() {
    return topoConstraint;
  }

  public void setTopoConstraint(TopologyConstraint topoConstraint) {
    this.topoConstraint = topoConstraint;
  }

  public UpdateConnectivityServiceRPCInputSchema state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public UpdateConnectivityServiceRPCInputSchema endPoint(ConnectivityServiceEndPoint endPoint) {
    this.endPoint = endPoint;
    return this;
  }

   /**
   * Get endPoint
   * @return endPoint
  **/
  @ApiModelProperty(value = "")
  public ConnectivityServiceEndPoint getEndPoint() {
    return endPoint;
  }

  public void setEndPoint(ConnectivityServiceEndPoint endPoint) {
    this.endPoint = endPoint;
  }

  public UpdateConnectivityServiceRPCInputSchema connConstraint(ConnectivityConstraint connConstraint) {
    this.connConstraint = connConstraint;
    return this;
  }

   /**
   * Get connConstraint
   * @return connConstraint
  **/
  @ApiModelProperty(value = "")
  public ConnectivityConstraint getConnConstraint() {
    return connConstraint;
  }

  public void setConnConstraint(ConnectivityConstraint connConstraint) {
    this.connConstraint = connConstraint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateConnectivityServiceRPCInputSchema updateConnectivityServiceRPCInputSchema = (UpdateConnectivityServiceRPCInputSchema) o;
    return Objects.equals(this.resilienceConstraint, updateConnectivityServiceRPCInputSchema.resilienceConstraint) &&
        Objects.equals(this.serviceIdOrName, updateConnectivityServiceRPCInputSchema.serviceIdOrName) &&
        Objects.equals(this.topoConstraint, updateConnectivityServiceRPCInputSchema.topoConstraint) &&
        Objects.equals(this.state, updateConnectivityServiceRPCInputSchema.state) &&
        Objects.equals(this.endPoint, updateConnectivityServiceRPCInputSchema.endPoint) &&
        Objects.equals(this.connConstraint, updateConnectivityServiceRPCInputSchema.connConstraint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resilienceConstraint, serviceIdOrName, topoConstraint, state, endPoint, connConstraint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateConnectivityServiceRPCInputSchema {\n");
    
    sb.append("    resilienceConstraint: ").append(toIndentedString(resilienceConstraint)).append("\n");
    sb.append("    serviceIdOrName: ").append(toIndentedString(serviceIdOrName)).append("\n");
    sb.append("    topoConstraint: ").append(toIndentedString(topoConstraint)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    endPoint: ").append(toIndentedString(endPoint)).append("\n");
    sb.append("    connConstraint: ").append(toIndentedString(connConstraint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

