/*
 * tapi-photonic-media API
 * tapi-photonic-media API generated from tapi-photonic-media@2018-12-10.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GetLinkDetailsRPCInputSchema
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-09T14:10:37.064+02:00")
public class GetLinkDetailsRPCInputSchema {
  @SerializedName("topology-id-or-name")
  private String topologyIdOrName = null;

  @SerializedName("link-id-or-name")
  private String linkIdOrName = null;

  public GetLinkDetailsRPCInputSchema topologyIdOrName(String topologyIdOrName) {
    this.topologyIdOrName = topologyIdOrName;
    return this;
  }

   /**
   * Get topologyIdOrName
   * @return topologyIdOrName
  **/
  @ApiModelProperty(value = "")
  public String getTopologyIdOrName() {
    return topologyIdOrName;
  }

  public void setTopologyIdOrName(String topologyIdOrName) {
    this.topologyIdOrName = topologyIdOrName;
  }

  public GetLinkDetailsRPCInputSchema linkIdOrName(String linkIdOrName) {
    this.linkIdOrName = linkIdOrName;
    return this;
  }

   /**
   * Get linkIdOrName
   * @return linkIdOrName
  **/
  @ApiModelProperty(value = "")
  public String getLinkIdOrName() {
    return linkIdOrName;
  }

  public void setLinkIdOrName(String linkIdOrName) {
    this.linkIdOrName = linkIdOrName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLinkDetailsRPCInputSchema getLinkDetailsRPCInputSchema = (GetLinkDetailsRPCInputSchema) o;
    return Objects.equals(this.topologyIdOrName, getLinkDetailsRPCInputSchema.topologyIdOrName) &&
        Objects.equals(this.linkIdOrName, getLinkDetailsRPCInputSchema.linkIdOrName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topologyIdOrName, linkIdOrName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLinkDetailsRPCInputSchema {\n");
    
    sb.append("    topologyIdOrName: ").append(toIndentedString(topologyIdOrName)).append("\n");
    sb.append("    linkIdOrName: ").append(toIndentedString(linkIdOrName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

