/*
 * tapi-arof API
 * tapi-arof API generated from tapi-arof.yang
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TopologyRef;
import java.io.IOException;

/**
 * LinkRef
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-09T14:13:03.153+02:00")
public class LinkRef {
  @SerializedName("topology-uuid")
  private String topologyUuid = null;

  @SerializedName("link-uuid")
  private String linkUuid = null;

  public LinkRef topologyUuid(String topologyUuid) {
    this.topologyUuid = topologyUuid;
    return this;
  }

   /**
   * Get topologyUuid
   * @return topologyUuid
  **/
  @ApiModelProperty(value = "")
  public String getTopologyUuid() {
    return topologyUuid;
  }

  public void setTopologyUuid(String topologyUuid) {
    this.topologyUuid = topologyUuid;
  }

  public LinkRef linkUuid(String linkUuid) {
    this.linkUuid = linkUuid;
    return this;
  }

   /**
   * Get linkUuid
   * @return linkUuid
  **/
  @ApiModelProperty(value = "")
  public String getLinkUuid() {
    return linkUuid;
  }

  public void setLinkUuid(String linkUuid) {
    this.linkUuid = linkUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkRef linkRef = (LinkRef) o;
    return Objects.equals(this.topologyUuid, linkRef.topologyUuid) &&
        Objects.equals(this.linkUuid, linkRef.linkUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topologyUuid, linkUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkRef {\n");
    
    sb.append("    topologyUuid: ").append(toIndentedString(topologyUuid)).append("\n");
    sb.append("    linkUuid: ").append(toIndentedString(linkUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

