/*
 * OBFN API
 * OBFN Configuration API
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WavelengthReference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2020-04-07T12:29:31.342+02:00[Europe/Rome]")
public class WavelengthReference {

  @SerializedName("central-frequency")
  private CentralFrequency centralFrequency = null;
  
  @SerializedName("wavelength-id")
  private Integer wavelengthId = null;
  
  public WavelengthReference centralFrequency(CentralFrequency centralFrequency) {
    this.centralFrequency = centralFrequency;
    return this;
  }

  
  /**
  * Get centralFrequency
  * @return centralFrequency
  **/
  @ApiModelProperty(value = "")
  public CentralFrequency getCentralFrequency() {
    return centralFrequency;
  }
  public void setCentralFrequency(CentralFrequency centralFrequency) {
    this.centralFrequency = centralFrequency;
  }
  
  public WavelengthReference wavelengthId(Integer wavelengthId) {
    this.wavelengthId = wavelengthId;
    return this;
  }

  
  /**
  * Get wavelengthId
  * @return wavelengthId
  **/
  @ApiModelProperty(value = "")
  public Integer getWavelengthId() {
    return wavelengthId;
  }
  public void setWavelengthId(Integer wavelengthId) {
    this.wavelengthId = wavelengthId;
  }
  
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WavelengthReference wavelengthReference = (WavelengthReference) o;
    return Objects.equals(this.centralFrequency, wavelengthReference.centralFrequency) &&
        Objects.equals(this.wavelengthId, wavelengthReference.wavelengthId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(centralFrequency, wavelengthId);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WavelengthReference {\n");
    
    sb.append("    centralFrequency: ").append(toIndentedString(centralFrequency)).append("\n");
    sb.append("    wavelengthId: ").append(toIndentedString(wavelengthId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



